name: Update My Configs
on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Combine
        run: |
          # 1. Скачиваем первую ссылку, пропускаем 6 строк и убираем пустые строки
          curl -sL "https://raw.githubusercontent.com/igareck/vpn-configs-for-russia/refs/heads/main/WHITE-CIDR-RU-all.txt" | tail -n +7 | grep -v '^$' > list.txt
          
          # 2. Добавляем пустую строку для разделения (необязательно, но полезно)
          echo "" >> list.txt
          
          # 3. Добавляем вторую ссылку и убираем пустые строки
          curl -sL "https://raw.githubusercontent.com/zieng2/wl/main/vless_lite.txt" | grep -v '^$' >> list.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add list.txt
          git commit -m "Update configs" || exit 0
          git push
