name: Update My Configs
on:
  schedule:
    - cron: '0 */3 * * *' # Обновление каждые 3 часа
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download and Combine
        run: |
          # Скачиваем первую ссылку, удаляем первые 6 строк (tail -n +7) и убираем пустые строки
          curl -s "https://raw.githubusercontent.com" | tail -n +7 | grep -v '^$' > list.txt
          
          # Добавляем пустую строку для разделения
          echo "" >> list.txt
          
          # Добавляем вторую ссылку без изменений (только убираем пустые строки)
          curl -s "https://raw.githubusercontent.com" | grep -v '^$' >> list.txt

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "action@github.com"
          git add list.txt
          git commit -m "Update configs from sources" || exit 0
          git push
